apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: dev
  labels:
    app: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: 10.100.248.2:5000/repository/nodejs_app/nodejs:latest
        ports:
          - containerPort: 3000
        env: 
          - name: HOST  
            value: mysql-h
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password      
          - name: DATABASE
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: database-name

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 3000       # The port that the service will serve on
      targetPort: 3000 # The port that the container listens on
      nodePort: 30030  # The port on each node that will be used to access the service